phrases:
  bot_name: Sylph
  help: 使い方教えて
  register_clan: \[(?<clanName>[\s\S]+)\]を登録して
  request_pin: ピン留めして
  request_unpin: ピン留め解除して
  register_members: \[(?<clanName>[\s\S]+)\]のメンバーを登録して
  create_challenge_report: \[(?<clanName>[\s\S]+)\]の凸報告場所を作って
  register_webhook: \[(?<clanName>[\s\S]+)\]の状況が変化したら \[(?<url>https?://[\w!\?/\+\-_~=;\.,\*&@#\$%\(\)'\[\]]+)\] に通知して
  create_boss_questionnaire: ボスアンケートを?作って
  boss_notification: (?<bossNumber>[1-5])(ボス)?に?行きたい人に通知して
  get_boss_questionnaire_result: アンケ(ート)?結果見せて
  create_damage_report: ここを\[(?<clanName>[\s\S]+)\]のダメージ報告場所にするよ
  register_cooperate_channel: ここを\[(?<clanName>[\s\S]+)\]の連携チャンネルにするよ
  boss_subjugation: (?<bossNumber>[1-5])(ボス)?討伐
  register_uncomplete_member_role: \[(?<clanName>[\s\S]+)\]の凸未完了者のロールを登録して
  challenge_report_guide: |-
    凸をしたら回数に応じてスタンプを押してね。
    持ち越しを持ったら持ち越し作成ボタンを教えてね。持ち越しを消化したら削除を押してね。
    作成された持ち越しメッセージに対して返信をすると、補足情報を入力できるよ。
    タスキルを使ったら黄色い警告スタンプを押してね。
  no_member_for_register_message: 登録対象が見つからないよ。登録対象のメンバー(もしくはロール)のメンションをつけてコマンドを打ってね。
  help_message_basic: |-
    基本的に全てのコマンドはメンションをつけてください。
    ---------------------------------------------------------------------------
  help_message_register_clan: |-
    コマンド : [クラン名]を登録して
    概要 : 新しいクランを登録します。
    使用例 : [テストクラン]を登録して
    ---------------------------------------------------------------------------
  help_message_register_members: |-
    コマンド : [クラン名]のメンバーを登録して
    概要 : クランのメンバーを登録します。登録をするメンバー、もしくはロールへのメンションをつけてください。
    使用例 : [テストクラン]のメンバーを登録して ＠メンバーロール ＠メンバー
    ---------------------------------------------------------------------------
  help_message_register_webhook: |-
    コマンド : [クラン名]の状況が変化したら [URL] に通知して
    概要 : 指定したクランのメンバーや凸状況が変化した際にPOSTリクエストを送信するWebhookのURLを設定します。
    使用例 : [テストクラン]の状況が変化したら [https://example.com/] に通知して
    ---------------------------------------------------------------------------
  help_message_register_create_report: |-
    コマンド : [クラン名]の凸報告場所を作って
    概要 : 開催中のクランバトルにおけるクランの凸報告場所を作ります。このメッセージに対して指定のリアクションをすると、凸状況が更新されます。
    使用例 : [テストクラン]の凸報告場所を作って
    ---------------------------------------------------------------------------
  help_message_create_boss_questionaire: |-
    コマンド : ボスアンケートを作って
    概要 : 行きたいボスを調査するアンケートスレッドを作成します。作成されたスレッドのメッセージに指定のリアクションをすることで、通知を受け取ったりできます。
    ---------------------------------------------------------------------------
  help_message_notify_boss_questionaire: |-
    コマンド : (1~5の番号)ボスに行きたい人に通知して
    概要 : チャンネル内で作成された最新のボスアンケートの結果を元に、指定した番号のボスのスタンプを押した人に対してメンションします。
    使用例 : 1に行きたい人に通知して
    ---------------------------------------------------------------------------
  help_message_get_result_boss_questionaire: |-
    コマンド : アンケート結果見せて
    概要 : チャンネル内で作成された最新のボスアンケートの結果を表示します。
    ---------------------------------------------------------------------------
  help_message_register_damage_report_channel: |-
    コマンド : ここを[クラン名]のダメージ報告場所にするよ
    概要 : コマンドを入力したチャンネルをダメージ報告場所に設定します。凸宣言用のUIを提供します。
    使用例 : ここを[テストクラン]のダメージ報告場所にするよ
    ---------------------------------------------------------------------------
  help_message_register_coopreate_channel: |-
    コマンド : ここを[クラン名]の連携チャンネルにするよ
    概要 : コマンドを入力したチャンネルをクランの連携用チャンネルに設定します。連携用チャンネルで実行されたコマンドは指定したクランに対するアクションと認識されます。
    使用例 : ここを[テストクラン]の連携用チャンネルにするよ
    ---------------------------------------------------------------------------
  help_message_boss_subjugation: |-
    コマンド : (1~5の番号)ボス討伐
    概要 : ダメージ報告の掃除コマンドと同様にダメージ報告を削除します。同時に、削除対象のメッセージを書き込んだユーザーにメンションをします。
    使用例 : 1ボス討伐
    ---------------------------------------------------------------------------
  help_message_register_uncomplete_member_role: |-
    コマンド：[クラン名]の凸未完了者のロールを登録して
    概要：3凸完了してない人に自動的に付与されるロールを登録します。登録するロールへのメンションが必要です。
    使用例：[テストクラン]の凸未完了者のロールを登録して
    ---------------------------------------------------------------------------
  help_message_pin: |-
    コマンド：ピン留めして
    概要：メッセージに対して返信することで、返信元のメッセージをピン留めします。
    ---------------------------------------------------------------------------
  help_message_unpin: |-
    コマンド：ピン留め外して
    概要：メッセージに対して返信することで、返信元のメッセージのピン留めを解除します。
    ---------------------------------------------------------------------------
  days_unit: '{day}日目'
  boss_questionnaire_message: 行きたいボスのスタンプ押してね
  boss_notify_message: ボスの凸を開始するよ
  cannot_find_boss_questionnaire_message: ボスアンケートのメッセージが見つからないよ。500個以上前のメッセージは見れないから、新しくアンケートを作ってね。
  cannot_find_boss_number_message: 通知したいボスの番号が見つからないよ。
  no_in_session_clan_battle_message: 開催中のクランバトルがないよ。
  no_damage_report_channels_message: ダメージ報告チャンネルがないよ。
  specific_boss_word: (?<bossNumber>[1-5])ボス
  boss_knockout_message: ボスが倒れたよ。
  create_damage_report_message: |
    このチャンネルをダメージ報告場所として設定するよ。
    凸をするボスのボタンを押すと、凸宣言の作成案内が開始されるよ。
    コメントを追記する場合は、作成された凸宣言に返信をしてね。
  cannot_get_role_message: ロールが見つからないよ。対象のロールに対してメンションをしてね。
  cannot_use_command_in_dm_message: このコマンドはダイレクトメッセージでは使えないよ。サーバー内のテキストチャンネルで実行してね。
  first_challenge_stamp: 1️⃣
  second_challenge_stamp: 2️⃣
  third_challenge_stamp: 3️⃣
  task_kill_stamp: ⚠️
  succeed_reaction: 👍
  failed_reaction: 🥺
  1_boss_stamp: 1️⃣
  2_boss_stamp: 2️⃣
  3_boss_stamp: 3️⃣
  4_boss_stamp: 4️⃣
  5_boss_stamp: 5️⃣
  interaction_delete_prompt: 削除してね。
  open_damage_input_form_label: ダメージ入力
  damage_input_form_message: ダメージを万単位(下4桁省略)で入力してね。
  damage_input_0_label: "0"
  damage_input_1_label: "1"
  damage_input_2_label: "2"
  damage_input_3_label: "3"
  damage_input_4_label: "4"
  damage_input_5_label: "5"
  damage_input_6_label: "6"
  damage_input_7_label: "7"
  damage_input_8_label: "8"
  damage_input_9_label: "9"
  damage_input_back_label: "←"
  damage_input_apply_label: "決定"
  delete_label: "削除"
  confirm_delete_damage_report_message: 自分のではないダメージ報告を消そうとしてるよ。間違えた場合は下にある"これらのメッセージを削除する"を押してね。ダメージ報告を削除しても問題ない場合は削除ボタンを押してね。
  no_clan_members_message: クランメンバーが一人も登録されてないよ。メンバー登録コマンドで登録してね。
  not_clan_member_message: クランメンバーとして登録されてないよ。メンバー登録コマンドで登録してもらってね。
  in_process_damage_report_template: "{bossNumber}ボス 進行中"
  confirmed_damage_report_template: "{bossNumber}ボス {damage}"
  regular_challenge: "本凸"
  carry_over: 持ち越し
  boss: ボス
  nowloading_message: 処理中...
  challenger_select_place_holder: 代理報告の時は、凸者を選択してね
  start_challenge_prompt_template: "{bossNumber}ボスに凸するよ。"
  challenging_boss_select_place_holder: 凸するボスを選んでね
  in_deleting_message: "削除中"
  page_label: "{page}ページ目に移動"
  request_rescue_label: 救援要請
  request_rescue_message: 救援求
  no_challenger_message: 希望者なし
  select_challenged_type_select_message: ボスと物理or魔法を選んでね
  create_carry_over_ui_label: 持ち越し作成
  1b_label: 1ボス-物理
  1m_label: 1ボス-魔法
  2b_label: 2ボス-物理
  2m_label: 2ボス-魔法
  3b_label: 3ボス-物理
  3m_label: 3ボス-魔法
  4b_label: 4ボス-物理
  4m_label: 4ボス-魔法
  5b_label: 5ボス-物理
  5m_label: 5ボス-魔法
  input_carry_over_challenged_type_prompt: 凸したボスと、物理 or 魔法を選択してください。
  input_carry_over_seconds_prompt: 持ち越し秒数を入れてね。1分は60秒にして。(例:1分10秒→70)
  time_out_input_message: 入力に時間がかかり過ぎたから、この命令は無効になったよ。このメッセージを削除して、やり直してね。
  confirm_delete_carry_over_message: 自分のではない持ち越しを消そうとしてるよ。間違えた場合は下にある"これらのメッセージを削除する"を押してね。持ち越しを削除しても問題ない場合は削除ボタンを押してね。
  retry_challenge_label: 再凸
