phrases:
  bot_name: Sylph
  help_command: 使い方教えて
  register_clan: \[(?<clanName>[\s\S]+)\]を登録して
  register_members: \[(?<clanName>[\s\S]+)\]のメンバーを登録して
  create_challenge_report: \[(?<clanName>[\s\S]+)\]の凸報告場所を作って
  register_webhook: \[(?<clanName>[\s\S]+)\]の状況が変化したら \[(?<url>https?://[\w!\?/\+\-_~=;\.,\*&@#\$%\(\)'\[\]]+)\] に通知して
  create_boss_questionnaire: ボスアンケートを?作って
  boss_notification_command: (?<bossNumber>[1-5])に?行きたい人に通知して
  get_boss_questionnaire_result_command: (?<bossNumber>[1-5])に?行きたい人を?教えて
  create_damage_report_command: ここを\[(?<clanName>[\s\S]+)\]のダメージ報告場所にするよ
  challenge_report_guide: |-
    凸をしたら回数に応じてスタンプを押してね。
    持ち越しを持ったら1回目は青、2回目は緑のチェックマークにスタンプを押してね。
    タスキルを使ったら黄色い警告スタンプを押してね。
  no_member_for_register_message: 登録対象が見つからないよ。登録対象のメンバー(もしくはロール)のメンションをつけてコマンドを打ってね。
  help_message: |-
    基本的に全てのコマンドはメンションをつけてください。
    ---------------------------------------------------------------------------
    コマンド : [クラン名]を登録して
    概要 : 新しいクランを登録します。
    使用例 : [テストクラン]を登録して
    ---------------------------------------------------------------------------
    コマンド : [クラン名]のメンバーを登録して
    概要 : クランのメンバーを登録します。登録をするメンバー、もしくはロールへのメンションをつけてください。
    使用例 : [テストクラン]のメンバーを登録して ＠メンバーロール ＠メンバー
    ---------------------------------------------------------------------------
    コマンド : [クラン名]の状況が変化したら [URL] に通知して
    概要 : 指定したクランのメンバーや凸状況が変化した際にPOSTリクエストを送信するWebhookのURLを設定します。
    使用例 : [テストクラン]の状況が変化したら [https://example.com/] に通知して
    ---------------------------------------------------------------------------
    コマンド : [クラン名]の凸報告場所を作って
    概要 : 開催中のクランバトルにおけるクランの凸報告場所を作ります。このメッセージに対して指定のリアクションをすると、凸状況が更新されます。
    使用例 : [テストクラン]の凸報告場所を作って
    ---------------------------------------------------------------------------
    コマンド : ボスアンケートを作って
    概要 : 行きたいボスを調査するアンケートスレッドを作成します。作成されたスレッドのメッセージに指定のリアクションをすることで、通知を受け取ったりできます。
    ---------------------------------------------------------------------------
    コマンド : (1~5の番号)に行きたい人に通知して
    概要 : チャンネル内で作成されたアーカイブされてない最新のボスアンケートスレッドの結果を元に、指定した番号のボスのスタンプを押した人に対してメンションします。
    使用例 : 1に行きたい人に通知して
    ---------------------------------------------------------------------------
    コマンド : (1~5の番号)に行きたい人を教えて
    概要 : チャンネル内で作成されたアーカイブされてない最新のボスアンケートスレッドの結果を元に、指定した番号のボスのスタンプを押した人の一覧を取得します。
    使用例 : 1に行きたい人を教えて
    ---------------------------------------------------------------------------
    コマンド : ここを[クラン名]のダメージ報告場所にするよ
    概要 : コマンドを入力したチャンネルをダメージ報告場所に設定します。このチャンネルで送られたメッセージはダメージ報告として処理されます。
    使用例 : ここを[テストクラン]のダメージ報告場所にするよ
    ---------------------------------------------------------------------------
  days_unit: '{day}日目'
  boss_questionnaire_thread_name: ボスアンケート
  boss_questionnaire_message: 行きたいボスのスタンプ押してね
  boss_notify_message: ボスの凸を開始するよ
  cannot_find_boss_questionnaire_thread: ボスアンケートのスレッドが見つからないよ。
  cannot_find_boss_questionnaire_message: ボスアンケートのメッセージが見つからないよ。100個以上前のメッセージは見れないから、新しくアンケートを作ってね。
  cannot_find_boss_number_message: 通知したいボスの番号が見つからないよ。
  no_in_session_clan_battle_message: 開催中のクランバトルがないよ。
  create_damage_report_message: |
    このチャンネルをダメージ報告場所として設定するよ。
    
    凸をする直前にここで"(1~5)ボス 進行中"と入力してね。代理の場合は"(1~5)ボス 名前 進行中"と入力してね。
    例：1ボス 進行中 or 2ボス ふー 進行中
    
    終了5秒前や、最後のUB発動直後等のキリのいいタイミングで止めたら、進行中メッセージを編集してダメージを報告してね。
    ダメージの後は補足情報等のテキストを入力してね。
    例：
      1ボス 2000 5秒前 ニャルUBあり
      2ボス ふー 1500 5s 打ち切り
      3ボス 0 事故救援求
    
    各値の間には半角スペースを入れてね。
  create_damage_report_error_message: |
    報告の形式が間違ってるよ。以下の形式のいずれかで入力してね。
    ・1ボス 進行中
    ・2ボス ふー 進行中
    ・1ボス 2000 5秒前 ニャルUBあり
    ・2ボス ふー 1500 5s 打ち切り
    ・3ボス 0 事故救援求
    
    各値の間には半角スペースを入れてね。
  first_challenge_stamp: 1️⃣
  second_challenge_stamp: 2️⃣
  third_challenge_stamp: 3️⃣
  first_carry_over_stamp: ☑️
  second_carry_over_stamp: ✅
  task_kill_stamp: ⚠️
  succeed_reaction: 👍
  failed_reaction: 🥺
  1_boss_stamp: 1️⃣
  2_boss_stamp: 2️⃣
  3_boss_stamp: 3️⃣
  4_boss_stamp: 4️⃣
  5_boss_stamp: 5️⃣