phrases:
  bot_name: Sylph
  register_clan: \[(?<clanName>[\s\S]+)\]を登録して
  register_members: \[(?<clanName>[\s\S]+)\]のメンバーを登録して
  create_challenge_report: \[(?<clanName>[\s\S]+)\]の凸報告場所を作って
  register_webhook: \[(?<clanName>[\s\S]+)\]の状況が変化したら \[(?<url>https?://[\w!\?/\+\-_~=;\.,\*&@#\$%\(\)'\[\]]+)\] に通知して
  create_boss_questionnaire: ボスアンケートを?作って
  boss_notification_command: (?<bossNumber>[1-5])に?行きたい人に通知して
  challenge_report_guide: |-
    凸をしたら回数に応じてスタンプを押してね。
    持ち越しを持ったら1回目は青、2回目は緑のチェックマークにスタンプを押してね。
    タスキルを使ったら黄色い警告スタンプを押してね。
  no_member_for_register_message: 登録対象が見つからないよ。登録対象のメンバー(もしくはロール)のメンションをつけてコマンドを打ってね。
  help_message: |-
    基本的に全てのコマンドはメンションをつけてください。
    ---------------------------------------------------------------------------
    コマンド : [クラン名]を登録して
    概要 : 新しいクランを登録します。
    使用例 : [テストクラン]を登録して
    ---------------------------------------------------------------------------
    コマンド : [クラン名]のメンバーを登録して
    概要 : クランのメンバーを登録します。登録をするメンバー、もしくはロールへのメンションをつけてください。
    使用例 : [テストクラン]のメンバーを登録して ＠メンバーロール ＠メンバー
    ---------------------------------------------------------------------------
    コマンド : [クラン名]の状況が変化したら [URL] に通知して
    概要 : 指定したクランのメンバーや凸状況が変化した際にPOSTリクエストを送信するWebhookのURLを設定します。
    使用例 : [テストクラン]の状況が変化したら [https://example.com/] に通知して
    ---------------------------------------------------------------------------
    コマンド : [クラン名]の凸報告場所を作って
    概要 : 開催中のクランバトルにおけるクランの凸報告場所を作ります。
    使用例 : [テストクラン]の凸報告場所を作って
    ---------------------------------------------------------------------------
    ---------------------------------------------------------------------------
    ---------------------------------------------------------------------------
    ---------------------------------------------------------------------------
    ---------------------------------------------------------------------------
    ---------------------------------------------------------------------------
    ---------------------------------------------------------------------------
  days_unit: '{day}日目'
  boss_questionnaire_message: 行きたいボスのスタンプ押してね
  boss_notify_message: ボスの凸を開始するよ
  cannot_find_boss_questionnaire_message: ボスアンケートが見つからないよ。1000個以上前のメッセージは見つけられないから、新しくアンケートを作ってね。
  no_in_session_clan_battle_message: 開催中のクランバトルがないよ。
  first_challenge_stamp: 1️⃣
  second_challenge_stamp: 2️⃣
  third_challenge_stamp: 3️⃣
  first_carry_over_stamp: ☑️
  second_carry_over_stamp: ✅
  task_kill_stamp: ⚠️
  succeed_reaction: 👍
  failed_reaction: 🥺
  1_boss_stamp: 1️⃣
  2_boss_stamp: 2️⃣
  3_boss_stamp: 3️⃣
  4_boss_stamp: 4️⃣
  5_boss_stamp: 5️⃣