version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

commands:
  set-heroku-env:
    description: set environment variable HEROKU_API_KEY and HOROKU_APP_NAME
    parameters:
      app-name:
        type: env_var_name
      api-key:
        type: env_var_name
    steps:
    - run: echo 'export HOROKU_APP_NAME="${<< parameters.app-name >>}"' >> $BASH_ENV
    - run: echo 'export HEROKU_API_KEY="${<< parameters.api-key >>}"' >> $BASH_ENV
  push-to-heroku:
    description: deploy specific directory to heroku via git
    parameters:
      directory:
        type: string
    steps:
    - run: git subtree push --prefix << parameters.directory >>/ https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git master

jobs:
  deploy:
    executor: heroku/default
    steps:
    - checkout
    - heroku/install
    - set-heroku-env:
        app-name: BOT_APP_NAME
        api-key: BOT_HEROKU_KEY
    - run: echo $HEROKU_APP_NAME
    - run: heroku ps:scale worker=0 --app ${HEROKU_APP_NAME}
    - set-heroku-env:
        app-name: API_APP_NAME
        api-key: API_HEROKU_KEY
    - push-to-heroku:
        directory: api
    - run: heroku run php artisan migrate
    - set-heroku-env:
        app-name: BOT_APP_NAME
        api-key: BOT_HEROKU_KEY
    - push-to-heroku:
        directory: bot-js
    - run: heroku ps:scale worker=1 --app ${HEROKU_APP_NAME}

workflows:
  version: 2
  deploy:
    jobs:
    - deploy:
        filters:
          branches:
            only:
            - main