version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

commands:
  set-heroku-env:
    description: set environment variable HEROKU_API_KEY and HOROKU_APP_NAME
    parameters:
      app-name:
        type: env_var_name
      api-key:
        type: env_var_name
    steps:
    - run: echo 'export HEROKU_APP_NAME="${<< parameters.app-name >>}"' >> $BASH_ENV
    - run: echo 'export HEROKU_API_KEY="${<< parameters.api-key >>}"' >> $BASH_ENV

jobs:
  deploy:
    executor: heroku/default
    steps:
    - checkout
    - heroku/install
    - set-heroku-env:
        app-name: API_APP_NAME
        api-key: API_HEROKU_KEY
    - run: echo $HEROKU_APP_NAME
    #- run: heroku ps:scale bot=0 --app ${HEROKU_APP_NAME}
    - run: git push https://heroku:${HEROKU_API_KEY}@git.heroku.com/${HEROKU_APP_NAME}.git main
    #- run: heroku run php artisan migrate --force --app ${HEROKU_APP_NAME}
    #- run: heroku ps:scale bot=1 --app ${HEROKU_APP_NAME}

workflows:
  version: 2
  deploy:
    jobs:
    - deploy:
        filters:
          branches:
            only:
            - main