version: '3'

services:
  database:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sylph
    volumes:
      - "./database:/var/lib/postgresql/data"

  cache:
    image: redis
    hostname: redis

  redis_commander:
    image: rediscommander/redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - cache

networks:
  default:
    external:
      name: sylph