version: '3'

services:
  database:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sylph
    tmpfs:
      - /var/lib/postgresql/data
    
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx/api.conf:/etc/nginx/conf.d/api.conf"
      - "unix_socket:/var/run/php-fpm"

  api:
    build:
      context: ..
      dockerfile: localenv/api/Dockerfile 
    volumes:
      - "unix_socket:/var/run/php-fpm"
      
  bot:
    build:
      context: bot
    volumes:
      - "../bot:/var/app"
 
networks:
  default:
    external:
      name: sylph

volumes:
  unix_socket: